server:
  port: 8082
spring:
  data:
    redis:
      connect-timeout: 2000
      host: redis
      port: 6379

token-client:
  urls:
    base-url: token-app:8081/api
    post-token-url: /tokens/
    
deposit-client:
  urls:
    base-url: deposit-app:8083/api
    post-deposit-url: /deposits/

movement-client:
  urls:
    base-url: movement-app:8084/api
    get-movement-url: /movements/

client-credentials:
  deposit-service:
    client-id: service-A
    password: 1234
  movement-service:
    client-id: service-B
    password: abcd
